language: node_js
node_js:
 - "7.4.0"
services:
 - mongodb
before_script:
 - mv src/travis.const.js src/const.js
script:
 - npm run cover
cache:
  directories:
  - node_modules
after_success:
 - cat coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls.js
