FROM node:22 AS builder

WORKDIR /app
COPY package-lock.json package.json ./
RUN npm ci
COPY . .
RUN npm run build || true

# Build the final image
RUN rm -rf node_modules
RUN npm ci --omit=dev

FROM node:22-slim AS runner
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY ./pages/ ./pages/
COPY ./favicon.ico .
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/c /app/c
CMD ["node", "/app/c/index.js"]
