#!/bin/bash

PIDFILE="/var/run/johnserver.pid"
SERVERLOC="/home/john/server/john2143.com"

start(){
    if [[ -f $PIDFILE ]]; then
        echo "John2143.com already running"
    else
        cd $SERVERLOC
        nohup nice -n -10 npm run startLog > /dev/null &
        echo $! > $PIDFILE
        echo Daemon Started $!
    fi
}

stop(){
    if [[ -f $PIDFILE ]]; then
        rkill $(cat $PIDFILE)
        echo "Killed process"
        rm $PIDFILE
    else
        echo "John2143.com not running"
    fi
}

case "$1" in
    start) start;;
    stop) stop;;
    restart) stop; start;;
    status) [[ -f $PIDFILE ]] && echo Running pid $(cat $PIDFILE) || echo "Stopped";;
    *) echo "Usage: $0 {start|stop|status|restart}"
esac
